export const data = [
    'Python',
    'JavaScript',
    'Java',
    'C#',
    'C++',
    'Ruby',
    'Go',
    'Swift',
    'TypeScript',
    'PHP',
    'Rust',
    'Kotlin',
    'Scala',
    'Objective-C',
    'Haskell',
    'Shell',
    'MATLAB',
    'R',
    'Dart',
    'Elixir',
    'Clojure',
    'HTML',
    'CSS',
    'SQL',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'SQLite',
    'Oracle',
    'Redis',
    'Elasticsearch',
    'Cassandra',
    'Firebase',
    'Apache Kafka',
    'Apache Hadoop',
    'Apache Spark',
    'Django',
    'Ruby on Rails',
    'Angular',
    'React',
    'Vue.js',
    'Node.js',
    'Spring Boot',
    'TensorFlow',
    'PyTorch',
    'ASP.NET',
    'Bootstrap',
    'Laravel',
    'WordPress',
    'Magento',
    'Docker',
    'Kubernetes',
    'Terraform',
    'Jenkins',
    'Git',
    'GitHub',
    'GitLab',
    'Bitbucket',
    'Jira',
    'Confluence',
    'Slack',
    'AWS',
    'Azure',
    'Google Cloud',
    'Heroku',
    'DigitalOcean',
    'Nginx',
    'Apache HTTP Server',
    'IIS',
    'Vagrant',
    'Puppet',
    'Chef',
    'Prometheus',
    'Grafana',
    'ELK Stack',
    'Splunk',
    'New Relic',
    'Datadog',
    'Selenium',
    'Junit',
    'Postman',
    'Swagger',
    'Kibana',
    'Logstash',
    'RabbitMQ',
    'ZeroMQ',
    'Apache Cassandra',
    'HashiCorp Vault',
    'Consul',
    'Elastic Stack',
    'OpenShift',
    'Packer',
    'Ansible',
    'SaltStack',
    'HAProxy',
    'NGINX Plus',
    'Apache Tomcat',
    'Memcached',
    'Hadoop',
    'Apache Hive',
    'Apache HBase',
    'Amazon Redshift',
    'MSSQL',
    'Oracle Database',
    'IBM DB2',
    'MariaDB',
    'Amazon Aurora',
    'Couchbase',
    'Neo4j',
    'GraphQL',
    'Kafka Streams',
    'Apache Flink',
    'IBM Watson',
    'Amazon S3',
    'Azure Blob Storage',
    'Google Cloud Storage',
    'Ethereum',
    'Hyperledger Fabric',
    'Solidity',
    'Truffle',
    'Web3',
    'Geth',
    'Parity',
    'Flutter',
    'Xamarin',
    'React Native',
    'Ionic',
    'NativeScript',
    'Electron',
    'Unity',
    'Unreal Engine',
    'Cocos2d',
    'SFML',
    'Qt',
    'Pandas',
    'NumPy',
    'SciPy',
    'Matplotlib',
    'Scikit-learn',
    'PySpark',
    'NLTK',
    'Flask',
    'Express',
    'Ruby Sinatra',
    'Symfony',
    'CakePHP',
    'CodeIgniter',
    'Zend Framework',
    'Drupal',
    'Joomla',
    'Shopify',
    'WooCommerce',
    'BigCommerce',
    'Keras',
    'Sass',
    'Webpack',
    'Maven',
    'Tailwind',
    'styled-components',
    'Blazor',
    'Nest.js',
    'Prisma',
    'Drizzle',
    'Sequelize',
    'TypeORM',
    'Mongoose',
    'Knex.js',
    'Hibernate',
    'Redux',
    'Linux',
];
